<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartamentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sectors = [
            'GCA-Serviços de Apoio',
            'GCRI-Subordinação Directa',
            'DIT-Divisão de Transporte Sul',
            'DRCM-ASC Kampfumo',
            'GEDE-GA Estatistica Desempenho Empresari',
            'DSG-Dep.to de Patrimonio',
            'DACA-Dep.to Formação Desenvolvimento',
            'DHSS-Dep.to Saúde Ocupacional e AMM',
            'DDN-Unidades de Gestão de Projectos',
            'GEPC-Serviços de Apoio',
            'DPSE-Dep.to de Planeamento de Sistemas',
            'GCRI-Serviços de Apoio',
            'DID-Subordinação Directa',
            'DFC-Dep.to de Contas a Pagar',
            'GCA-Departamento de Segurança',
            'GAJ-Serviços de Apoio',
            'DRS-ASC Inhambane',
            'DRN-ASC Nampula',
            'DRC-ASC Chimoio',
            'DPSE-Dep.to de Engenharia',
            'DPSE-Dep.to Qualid Planeamento Ambiental',
            'DEP-GA Gestão de Projectos',
            'DOS-Dep.to de Operação de Sistemas',
            'DIP-Divisão de Produção Centro Norte',
            'GAR-Serviços de Apoio',
            'DSG-Serviços de Apoio',
            'DIP-Divisão de Produção Sul',
            'DRPM-ASC Infulene',
            'DIP-Serviços de Apoio',
            'DGRH-Dep.to Politicas Desenvolv e Genero',
            'DER-Dep Energias Renovaveis Dentro Rede',
            'DDN-Serviços de Apoio',
            'DID-Dep.to de Efeciência Energética',
            'DIP-GA Planeamento Prod. e Estatistica',
            'GAJ-Subordinação Directa',
            'DEP-Serviços de Apoio',
            'DFC-Serviços de Apoio',
            'DDN-Unidade Monitoria Mobilização Fundos',
            'GCRI-Director(a)',
            'GCA-Subordinação Directa',
            'GAJ-Director(a)',
            'GEDE-Serviços de Apoio',
            'DER-Serviços de Apoio',
            'ADMIN RH - Dep.to de Fundo Social',
            'DOM-Dep.to de Serviço ao Cliente',
            'DPRCP-Dep.to Sistemas Inform. Geografica',
            'DOM-Serviços de Apoio',
            'DRCM-ASC Kaguava',
            'DOM-Dep.to de Trocas Comerciais',
            'DRCM-ASC Kamubuacuna',
            'DGRH-Dep.to de Serviços Partilhados',
            'DTI-Dep.to Aplicações Corporativas',
            'DRCM-ASC Kamaxakeni',
            'GIA-Subordinação Directa',
            'DACA-Dep.to de Gestão de Conhecimento',
            'DRCM-ASC Kamavota',
            'DTI-Director(a)',
            'DIC-Serviços de Apoio',
            'DRPM-Gabinete Serviços de Apoio',
            'GAR-GA Auditoria de Processos',
            'DTI-Dep.to Redes Corporativas Equipament',
            'DTI-GA Estrategias e Programa',
            'DTI-Dep.to Centro Dados Ciber Segurança',
            'DIC-Dep.to de Serviço ao Cliente',
            'DIA-Dep.to de Analise e Desenvolvimento',
            'DTI-Serviços de Apoio',
            'DRC-ASC Quelimane',
            'DRS-ASC Vilanculos',
            'DACA-Academiada EDM-Director',
            'DRPM-ASC Boane',
            'DRPM - ASC Machava',
            'DEP-GA Monitoria, IMS Mobilização Fundos',
            'DPSE-Director(a)',
            'DIT-Serviços de Apoio',
            'PCA - Subordinação Directa',
            'DIT-Divisão de Transporte Centro',
            'DPRCP-Dep.to Serviços Tecnico Comerciais',
            'DEP-Director(a)',
            'DIT-Dep.to de Telecomunicações e SCADA',
            'DOS-Director(a)',
            'DER-Director(a)',
            'DIT-Divisão de Transporte Norte',
            'GIA-Serviços de Apoio',
            'DIT-Dep.to de Protecções',
            'DIT-Divisão de Transporte Centro Norte',
            'DRS-ASC Chókwe',
            'DID-Dep.to Planeamento de Infraestrutura',
            'DFC-Dep.to de Contas a Receber',
            'DSG-Dep.to de Logistica',
            'DGRH-Serviços de Apoio',
            'DID-Dep.to de Manutenção',
            'DIA-Dep.to de Procurement',
            'DPRCP-Dep.to Prev. Vand. Infra. Eq. Elec',
            'DFC-Dep.to de Contabilidade',
            'DFC-Dep.to de Tesouraria',
            'GAR-GA Auditoria de Investigação',
            'DDN-Director(a)',
            'DFC-Dep.to de Planificação Financ e Orça',
            'DIA-Serviços de Apoio',
            'GEDE-Director(a)',
            'DGRH-Dep.to Serviço ao Cliente Interno',
            'DHSS-Director(a)',
            'DHSS-Serviços de Apoio',
            'DACA-Serviços de Apoio',
            'DSG-Director(a)',
            'Admin(a)-Recursos Humanos',
            'GAR-Director(a)',
            'DRPM-ASC Matola',
            'DPRCP-Dep.to Controle Medição Metrologia',
            'GCA-Director(a)',
            'DIC-GA Marketing',
            'DIC-Dep.to de Ciclo Comercial',
            'DRC-ASC Beira',
            'DRPM-Gabinete de Distribuição',
            'DRN-ASC Lichinga',
            'DRPM-Gabinete Planeamento e Estatistica',
            'DRS-ASC Xai-Xai',
            'DRN-ASC Pemba',
            'DPRCP-Serviços de Apoio',
            'DRC-ASC Tete',
            'DRN - ASC Cuamba',
            'DRN-ASC Angoche',
            'GEPC-GA Provedoria ao Cliente',
            'DRN - ASC Nacala',
            'DRC-Gabinete de Distribuição',
            'DRC-ASC Mocuba',
            'DRN-Gabinete Planeamento e Estatistica',
            'DGRH-Director(a)',
            'DRN-Gabinete Serviços de Apoio',
            'DOS-Serviços de Apoio',
            'DRN-Gabinete Comercial',
            'DRN-Gabinete de Distribuição',
            'DRN - Director(a)',
            'DPRCP-Director(a)',
            'DRS-Director(a)',
            'DID-Dep.to de Operação',
            'DRCM-Director(a)',
            'DRS-Gabinete Comercial',
            'DRPM-Gabinete Comercial',
            'DRCM-Gabinete Serviços de Apoio',
            'DRC-ASC Caia',
            'DOM-Director(a)',
            'DRC-Gabinete Planeamento e Estatistica',
            'DRC-Gabinete Serviços de Apoio',
            'DFC-Director(a)',
            'DID-Director(a)',
            'DOS-Dep.to Planeamento Super. Manutenção',
            'DIT-Director(a)',
            'DIP-Director(a)',
            'DRPM-Director(a)',
            'DHSS-Dep.to Segurança no Trabalho',
            'DRC-Director(a)',
            'DIC-GA Processos e Tarifas',
            'DRS-Gabinete Planeamento e Estatistica',
            'DRCM-Gabinete Planeamento e Estatistica',
            'ADMIN DCI - Subordinação Directa',
            'DIC-Director(a)',
            'DRCM-Gabinete de Distribuição',
            'DRCM-Gabinete Comercial',
            'GEPC-Director(a)',
            'DIC-Dep.to de Grandes Clientes',
            'DER-Dep Energias Renovaveis Fora Rede',
            'DPSE-Serviços de Apoio',
            'DRC-Gabinete Comercial',
        ];

        foreach ($sectors as $name) {
            DB::table('departamentos')->updateOrInsert(
                ['name' => $name],
                [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
